package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Job saves as a favorite")
    void generatedTest() {
        step("Open 'https://careers.king.com/'", () -> {
            step("// todo: just add selenium action");
        });

        step("Open Jobs Tab", () -> {
            step("// todo: just add selenium action");
        });

        step("Set 'QA Specialist - Candy Crush' in the search field", () -> {
            step("// todo: just add selenium action");
        });

        step("Check if there is 'QA Specialist - Candy Crush' in the list", () -> {
            step("// todo: just add selenium action");
        });

        step("Click a hurt sign to add the job as a favorite", () -> {
            step("// todo: just add selenium action");
        });

        step("Open \"Saved jobs\" tab", () -> {
            step("// todo: just add selenium action");
        });

        step("Check if there is new saved job", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://careers.king.com/'", () ->
            open("https://careers.king.com/"));

        step("Page title should have text 'Making the world playful | King Careers'", () -> {
            String expectedTitle = "Making the world playful | King Careers";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://careers.king.com/'", () ->
            open("https://careers.king.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}